### ISSUE TITLE
主题打不开，报错

### ISSUE THREAD

**Issue by viogami** [lumirant/Ayakin-Theme#1]
是不是哪里调用函数错了？还是版本问题？
报错信息为：
Call to a member function format() on null

**Comment by lumirant** [comment]
您的邮件已收到，我将会在三周内对有需要回复的邮件进行回复，请耐心等候，如三周内未收到回信，可重复发送该邮件

**Comment by lumirant** [comment]
你好，感谢你贡献了这个问题。

经过一段时间的排查，发现问题主要是由`/component/topPosts.php`文件引起的，分别发生在第11、14、18行等位置。

该问题主要是由于当初次切换至Ayakin主题后，没有在设置项中为`置顶文章`填入内容，导致主题在获取置顶文章时接收到了`NULL`值，继而让主题后续操作无法正常完成，从而意外中断了系统运行并抛出了此错误。

另外，在修复此问题的过程中，同时也发现了诸如`header.php`、`index.php`等文件的某些位置存在着类似的安全隐患，后续已为这些位置的代码上下文加入了非空判断保护，保证主题在没有获取到置顶文章时不会执行相关代码。

相关问题现已成功修复并更新至该Github仓库，经多次测试，并不会影响主题原本功能，你可以将`/usr`目录下的`Ayakin`文件夹整个删除，而后重新下载主题资源文件到同目录下，按照Typecho主题安装方法正常重装主题，并在网站后台启用Ayakin主题即可。

再次感谢你对代码改进做的贡献，如果有任何后续问题，可随时提Issue寻求帮助。

**Comment by viogami** [comment]
幸苦了，好高效，感谢你的修复❤️ 
我也猜测可能设置里的默认信息没填，没想到是置顶文章hhh

**Comment by lumirant** [comment]
是的呢，我也没想到会有这个问题，因为演示站一直都能运行，发布前也没来得及做太多细致的测试，感谢提出这个问题~
